# Generated by Django 3.0.5 on 2020-09-17 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gossips_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='username must be alphanumeric and length  should be grater than 5', regex='^[0-9a-zA-Z_]{1,}$')])),
                ('real_name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='your name should  contain only alpahabets', regex='^[a-zA-Z ]+$')])),
                ('profile_pic_url', models.URLField(default='https://google.com', max_length=1000)),
                ('bio', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='not eligible phone number', regex='^(91)[0-9]{10}$')])),
                ('public_key', models.CharField(default=' ', max_length=500)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
