# Generated by Django 3.0.5 on 2020-09-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gossips_account',
            name='bio',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='gossips_account',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='gossips_account',
            name='profile_pic_url',
            field=models.URLField(default='https://google.com', max_length=1000),
        ),
    ]
